### ISSUE TITLE
Fork to the collective?

### ISSUE THREAD

**Issue by djay** [collective/sc.contentrules.localrole#1]
Hi @ericof we want to add a feature to this plugin (or make a similar one). Should be fork this into the collective and rename it to collective.contentrules.localrole?

The feature we want to add is to enable the principle id to come from a field of the content

**Comment by ericof** [comment]
@djay Move it to the collective, about renaming it I would say it is your call ;-)

**Comment by hvelarde** [comment]
@rodfersou the package lives now on the collective.

**Comment by instification** [comment]
@ericof @hvelarde 

we have started working on the proposed changes in #2

Do you want to review PR's changes or are we ok to merge them ourselves?

I will make another issue for whether or not to change the name to be consistent with other contentrules packages, but if we were to do so then either the package owner will need to do it or you will need to give us permissions on the repo.

**Comment by hvelarde** [comment]
@instification we're not using this package anymore; feel free to do whatever changes you need, just keep things well documented.
